name: data-converter test suite

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8==6.1.0

    - name: Analysing the code with Flake8
      run: |
        flake8 --ignore=E501,E271,E272,W602,W504 --exclude=submodules

    - name: Run tests
      run: |
        python -m unittest
